name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup cloud-init
        run: |
          apt-get update
          apt-get install cloud-init
          cloud-init --version
     
      - name: Validate cloud-init schema
        run: |
          cloud-init schema -c ubuntu/http/user-data
 
      - uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest
