name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      - name: Setup cloud-init
        run: |
          cloud-init --version
 
      - uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest
